name: Android CI

on:
  push:
    branches:
    - '**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        chmod +x ./gradlew
        ./gradlew test
    - name: Run AndroidTests
      uses: faruktoptas/android-github-actions-emulator@1.1.0
      with:
        api-level: 27
        script: ./gradlew connectedCheck
