name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Tests
      run: |
        chmod +x ./gradlew
        ./gradlew test
    - name: Run AndroidTests
      uses: faruktoptas/android-github-actions-emulator@1.1.0
      with:
        api-level: 29
        script: ./gradlew connectedCheck
